# Data Preparation
ทำ data cleansing สำหรับข้อมูล bangkok_traffy.csv เพื่อสร้างโมเดลทำนายการแก้ไขปัญหาเวลาในการทำ

In [1]:
!pip install pandas numpy scikit-learn seaborn matplotlib requests beautifulsoup4 pandas

Requirement already satisfied: pandas in c:\users\ten\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: numpy in c:\users\ten\anaconda3\lib\site-packages (1.24.3)
Requirement already satisfied: scikit-learn in c:\users\ten\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: seaborn in c:\users\ten\anaconda3\lib\site-packages (0.12.2)
Requirement already satisfied: matplotlib in c:\users\ten\anaconda3\lib\site-packages (3.7.1)
Requirement already satisfied: requests in c:\users\ten\anaconda3\lib\site-packages (2.31.0)
Requirement already satisfied: beautifulsoup4 in c:\users\ten\anaconda3\lib\site-packages (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ten\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\ten\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: tzdata>=2022.1 in c:\users\ten\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: scipy>=1.5.0 in c:\users\ten\anaconda3\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\ten\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ten\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ten\anaconda3\lib\site-packages (from matplotlib) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\ten\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ten\anaconda3\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\ten\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\ten\anaconda3\lib\site-packages (from matplotlib) (23.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\ten\anaconda3\lib\site-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ten\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ten\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ten\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ten\anaconda3\lib\site-packages (from requests) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ten\anaconda3\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: soupsieve>1.2 in c:\users\ten\anaconda3\lib\site-packages (from beautifulsoup4) (2.4)
Requirement already satisfied: six>=1.5 in c:\users\ten\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('bangkok_traffy.csv')

In [4]:
df_clean = df

In [ ]:
# ค้นหาคำว่า "เขค/อำเภอ" ตามด้วยช่องว่าง(มีหรือไม่มีก็ได้) แล้วดึงข้อความข้างหลังออกมา
# (?<=...) คือ Lookbehind เพื่อเช็คคำนำหน้าแต่ไม่เก็บคำนำหน้านั้นมา
pattern_district = r'(?:เขต|อำเภอ|อ\.)\s*([ก-๙a-zA-Z0-9\-\.]+)'

# สร้างตัวแปรชั่วคราวที่ดึงค่าเขตมาจาก Address
extracted_dist = df_clean['address'].str.extract(pattern_district, expand=False)

# เติมลงในช่องที่เป็น NaN เท่านั้น
df_clean['district'] = df_clean['district'].fillna(extracted_dist)

# บางครั้งอาจมีช่องว่างติดมา ให้ตัดออก
df_clean['district'] = df_clean['district'].str.strip()
df_clean.dropna(subset=['district'])

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
0,2021-FYJTFP,{ความสะอาด},เขตบางซื่อ,ขยะเยอะ,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53084,13.81865",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,บางซื่อ,กรุงเทพมหานคร,2021-09-03 12:51:09.453003+00,เสร็จสิ้น,NaN,0,2022-06-04 15:34:14.609206+00
1,2021-CGPMUN,"{น้ำท่วม,ร้องเรียน}","เขตประเวศ,ฝ่ายโยธา เขตประเวศ",น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.66709,13.67891",189 เฉลิมพระเกียรติ ร.9 แขวง หนองบอน เขต ประเว...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-09-19 14:56:08.924992+00,เสร็จสิ้น,4.0,0,2022-06-21 08:21:09.532782+00
2,2021-7XATFA,{สะพาน},เขตสาทร,สะพานลอยปรับปรุงไม่เสร็จตามกำหนด\nปากซอย สาทร12,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52649,13.72060",191/1 ถนน สาทรเหนือ แขวง สีลม เขตบางรัก กรุงเท...,ยานนาวา,สาทร,กรุงเทพมหานคร,2021-09-26 05:03:52.594898+00,เสร็จสิ้น,NaN,0,2022-06-06 01:17:12.272904+00
3,2021-9U2NJT,{น้ำท่วม},"เขตบางซื่อ,ฝ่ายโยธา เขตบางซื่อ",น้ำท่วม,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53099,13.81853",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,บางซื่อ,กรุงเทพมหานคร,2021-10-14 10:45:27.713884+00,เสร็จสิ้น,NaN,0,2022-09-08 08:35:43.784519+00
4,2021-DVEWYM,"{น้ำท่วม,ถนน}","เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.59165,13.82280",702 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขตลาดพร้าว...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,2021-12-09 12:29:08.408763+00,เสร็จสิ้น,5.0,0,2022-08-12 07:18:44.884945+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787021,KDDNBP,{ร้องเรียน},เขตหนองจอก,ศูนย์เรื่องราวร้องทุกข์ ได้รับการประสานผ่านระบ...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.86304,13.85633",เขตหนองจอก กรุงเทพมหานคร : VV47+G6M แขวงกระทุ่...,กระทุ่มราย,หนองจอก,กรุงเทพมหานคร,2025-01-16 02:50:24.112172+00,กำลังดำเนินการ,NaN,0,2025-01-16 02:50:26.781334+00
787022,RYM99G,"{ความสะอาด,ถนน}","เขตคลองสาน,ฝ่ายสิ่งแวดล้อมฯ เขตคลองสาน",ปัญหา: บริเวณตลาดพระเครื่องพญาไม้ พบร้านอาหารต...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.49651,13.73469",39 ถ. สมเด็จเจ้าพระยา แขวงสมเด็จเจ้าพระยา เขตค...,สมเด็จเจ้าพระยา,คลองสาน,กรุงเทพมหานคร,2025-01-16 02:51:28.8957+00,กำลังดำเนินการ,NaN,0,2025-01-16 02:53:23.119455+00
787023,2025-BDQ87Y,"{ร้องเรียน,ต้นไม้,ความปลอดภัย}",เขตราชเทวี,ต้นไม้บริเวณดังกล่าวช่วงโคนต้นไม้มันแห้งเหมือน...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53975,13.76426",10 ถ. ราชวิถี แขวงถนนพญาไท เขตราชเทวี กรุงเทพม...,ถนนพญาไท,ราชเทวี,กรุงเทพมหานคร,2025-01-16 02:52:33.878797+00,รอรับเรื่อง,NaN,0,2025-01-16 02:52:38.17364+00
787024,EZCZZU,{ถนน},เขตจอมทอง,ปัญหา: พบโรงกลึง (ไม่ทราบชื่อ) ทำงานบนพื้นผิวจ...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.46226,13.67672",123 แขวงบางมด เขตจอมทอง กรุงเทพมหานคร 10150 ปร...,บางมด,จอมทอง,กรุงเทพมหานคร,2025-01-16 02:53:27.583947+00,กำลังดำเนินการ,NaN,0,2025-01-16 02:53:30.250517+00
787025,2025-E7CTFD,{จราจร},"เขตสวนหลวง,สำนักการจราจรและขนส่ง กรุงเทพมหานคร...",จริงๆไม่ใช่เขตสวนหลวงแต่ที่ปักเป็นสวนหลวงเพราะ...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.65165,13.73036",2998 ถ. พัฒนาการ แขวงสวนหลวง เขตสวนหลวง กรุงเท...,สวนหลวง,สวนหลวง,กรุงเทพมหานคร,2025-01-16 02:53:34.290375+00,กำลังดำเนินการ,NaN,0,2025-01-16 02:58:02.568451+00

เติมข้อมูล District ที่เป็นค่าว่าง (NaN) โดยใช้ Regex ดึงชื่อเขตหรืออำเภอมาจากคอลัมน์ Address แล้วตัดช่องว่างส่วนเกินออก

In [6]:
#Drop columns ที่ไม่จำเป็นออก
cols_to_drop = [
    "photo",
    "photo_after",   
    "address",
    "subdistrict",
    "province",
    "state",          
]
df_clean = df_clean.drop(columns=cols_to_drop, errors="ignore")
df_clean.columns = df_clean.columns.str.strip()
df_clean["star"] = df_clean["star"].fillna(0)
df_clean["count_reopen"] = df_clean["count_reopen"].fillna(0)
df_clean["organization"] = df_clean["organization"].fillna("Unknown")

ลดมิติข้อมูล (Drop Unnecessary Columns): ตัดคอลัมน์ที่ไม่ส่งผลดีต่อโมเดลออก
    
    - ลด Noise: ตัด ticket_id (ไม่มีความหมายเชิงพฤติกรรม) และ address/subdistrict (มีความหลากหลายสูง/High Cardinality) เพื่อป้องกันโมเดลจดจำข้อมูลจำเพาะเกินไป (Overfitting)  
    - ป้องกัน Data Leakage: ตัด photo_after เนื่องจากเป็นข้อมูลที่เกิดขึ้น หลัง การทำนาย
    - ขอบเขตงาน: ตัด photo เนื่องจากโปรเจกต์นี้ไม่ครอบคลุมการประมวลผลภาพ (Image Processing)
จัดรูปแบบชื่อคอลัมน์ (Standardize Headers): ตัดช่องว่างส่วนเกินเพื่อความถูกต้องในการเรียกใช้งาน
จัดการค่าสูญหาย (Imputation): แทนที่ star ที่เป็นค่าว่างด้วย 0 (อนุมานว่าไม่มีการให้คะแนน) แทนที่ count_reopen ที่เป็นค่าว่างด้วย 0 และแทนที่ organization เป้น "Unknown"

In [7]:
#Prep For interval
df_clean['timestamp'] = pd.to_datetime(df_clean['timestamp'], errors='coerce', utc=True)
df_clean['timestamp'].dtype
df_clean = df_clean.dropna(subset=["timestamp"])
df_clean['day'] = df_clean['timestamp'].dt.day_name().str[:3]   # Mon, Tue, Wed...
df_clean['hour'] = df_clean['timestamp'].dt.hour                # 0–23
df_clean["month"] = df_clean["timestamp"].dt.month
df_clean["year"] = df_clean["timestamp"].dt.year

เตรียมข้อมูลเวลา (Temporal Feature Engineering) โดยคัดกรองข้อมูลที่เวลาไม่ถูกต้องออก และแตกย่อย Timestamp เป็นฟีเจอร์ย่อย (วัน, ชั่วโมง, เดือน, ปี) เพื่อให้โมเดลจับ Pattern ของช่วงเวลาได้ละเอียดขึ้น

In [8]:
coords_split = df_clean["coords"].str.split(",", expand=True)
df_clean["lat"] = pd.to_numeric(coords_split[0], errors="coerce")
df_clean["lon"] = pd.to_numeric(coords_split[1], errors="coerce")
df_clean = df_clean.drop(columns=["coords"])

แยกค่า Latitude , Longitude ใน column 'coords' มาใส่ใน column 'lat' และ 'lon' ที่สร้างใหม่ตามลำดับ

In [9]:
# นำมาสร้าง target 
df_clean["last_activity"] = pd.to_datetime(df_clean["last_activity"], errors="coerce", utc=True)
df_clean["resolution_time_hours"] = (df_clean["last_activity"] - df_clean["timestamp"]).dt.total_seconds()/3600

# แล้วค่อย drop ทิ้ง
df_clean = df_clean.drop(columns=["last_activity"], errors="ignore")

# สร้าง column isLate ขึ้นมาโดยกำหนดให้เกิน 7 วัน แปลว่าช้า

# ตั้ง threshold (หน่วย: ชั่วโมง)
late_threshold = 168  # 7 วัน
# สร้างคอลัมน์ isLate (1 = ช้า, 0 = ทันเวลา)
df_clean["isLate"] = (df_clean["resolution_time_hours"] > late_threshold).astype(int)

df_clean["isLate"].value_counts(normalize=True)

isLate
1    0.528012
0    0.471988
Name: proportion, dtype: float64

เนื่องจากเราจะทำฌมเดลเพื่อทำนายว่าการแก้ปัญหาในแต่ละ ticket_id จะช้าหรือทำทันเวลา เราได้สร้าง column 'resolution_time_hours' 
เพื่อมาทำ column 'isLate' โดย isLate จะเป็น 1 เมื่อ resolution_time_hours มีค่ามากกว่า 168 ชั่วโมง (7วัน)

In [10]:
urgency_map = {
    'ความปลอดภัย': 5, 'น้ำท่วม': 5, 'สะพาน': 5, 'สายไฟ': 5,
    'การเดินทาง': 4, 'ถนน': 4, 'ท่อระบายน้ำ': 4, 'แสงสว่าง': 4,
    'PM2.5': 3, 'เสียงรบกวน': 3, 'คนจรจัด': 3, 'กีดขวาง': 3, 'ทางเท้า': 3,
    'ความสะอาด': 2,'สัตว์จรจัด': 2, 'คลอง': 2, 'ห้องน้ำ': 2, 'ต้นไม้': 2, 'จราจร': 2,
    'ป้าย': 1, 'ป้ายจราจร': 1 ,'ร้องเรียน':1, 'แจ้งปัญหา':1, 'เสนอแนะ':1, 'สอบถาม':1
}


def calculate_urgency(type_string):
    if pd.isna(type_string):
        return 1 # ถ้าเป็นค่าว่าง (NaN) ให้ค่าต่ำสุด (หรือจะแก้เป็น 2.5 ด้วยก็ได้ครับ)
    
    # 1. Clean string
    cleaned_string = type_string.replace('{', '').replace('}', '')
    
    # 2. Split
    tags = cleaned_string.split(',')
    
    # 3. Map & Max (จุดที่แก้ไข)
    # เปลี่ยนเลข 1 ด้านหลังเป็น 2.5
    scores = [urgency_map.get(tag.strip(), 2.5) for tag in tags if tag.strip() != '']
    
    # กรณี input เป็น {} ว่างๆ ไม่มีข้อความข้างใน
    if not scores:
        return 1 # หรือจะเปลี่ยนเป็น 2.5 ถ้าต้องการให้เคสว่างๆ มีค่ากลางๆ
        
    return max(scores)

df_clean['urgency_score'] = df_clean['type'].apply(calculate_urgency)

เนื่องใน column 'type' เก็บข้อมูลประเภทการเร้องเรียงต่างเป็น set เราจึง map ค่าลำดับความสำคัญ กับเหตุการณ์ที่ร้องเรียงเรียนมาสร้างเป็น column 'urgency_score' (เป็นตัวบ่งบอกว่าเหตุการณืที่ร้องเรียนมาสำคัญไหม)

In [11]:
import os
out_dir = 'data'
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, 'bangkok_traffy_clean.csv')
df_clean.to_csv(out_path, index=False, encoding='utf-8-sig')
print('Saved cleaned traffy to', out_path)

Saved cleaned traffy to data\bangkok_traffy_clean.csv

In [12]:
df_clean.head()

,ticket_id,type,organization,comment,district,timestamp,star,count_reopen,day,hour,month,year,lat,lon,resolution_time_hours,isLate,urgency_score
0,2021-FYJTFP,{ความสะอาด},เขตบางซื่อ,ขยะเยอะ,บางซื่อ,2021-09-03 12:51:09.453003+00:00,0.0,0,Fri,12,9,2021,100.53084,13.81865,6578.718099,1,2
1,2021-CGPMUN,"{น้ำท่วม,ร้องเรียน}","เขตประเวศ,ฝ่ายโยธา เขตประเวศ",น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,ประเวศ,2021-09-19 14:56:08.924992+00:00,4.0,0,Sun,14,9,2021,100.66709,13.67891,6593.416835,1,5
2,2021-7XATFA,{สะพาน},เขตสาทร,สะพานลอยปรับปรุงไม่เสร็จตามกำหนด\nปากซอย สาทร12,สาทร,2021-09-26 05:03:52.594898+00:00,0.0,0,Sun,5,9,2021,100.52649,13.72060,6068.222133,1,5
3,2021-9U2NJT,{น้ำท่วม},"เขตบางซื่อ,ฝ่ายโยธา เขตบางซื่อ",น้ำท่วม,บางซื่อ,2021-10-14 10:45:27.713884+00:00,0.0,0,Thu,10,10,2021,100.53099,13.81853,7893.837797,1,5
4,2021-DVEWYM,"{น้ำท่วม,ถนน}","เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,ลาดพร้าว,2021-12-09 12:29:08.408763+00:00,5.0,0,Thu,12,12,2021,100.59165,13.82280,5898.826799,1,5